hash-format = "sha256"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "d8ab469fa67e5ffe3487eaa644d3dcbb15865e8b0ee7f1118725e20b11e871fc"
metafile = true

[[files]]
file = "mods/adorn.pw.toml"
hash = "e771415712c8349da1f4aab0b263c9207bf60a778fd69e8d6e5d53258becd09e"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "e1dbd4b5d49d19f6d21e019802fe6c215bbe51694322ffb6a94664cbaf7d2384"
metafile = true

[[files]]
file = "mods/altorigingui.pw.toml"
hash = "51f02f245112a45eb6a751c5a56389ed4f53cee33502e610249abf1ac3e31a76"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "0a71df686303b605ecb7546ecec9fefa6db81621985e0817be15a42246982cbd"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "448704fce71e9a24a749ead5d39ddce609af636e70dfb6f181f21ae0c14f0373"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "55109c7480496fd2e85b2b69423607fd01763f39ec1411c7de598cbbb9a5d9f6"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "302c338b3662fdee1078bedd9df58db70d1ddbec10c98580075071aeed2947cb"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "2cf662d9e53e77bbeb0b9cb1d16da480ebab2712693f449610d989cf8bd180c3"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "61b530886289590118dbc5ab12b96fadce5a89f5c500c5ea2cea6580ee09aad2"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "06477ff0796f0bfb7aa20396b85bc82b83a2a80be3dac97403ceaf60e41e6d1e"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "313a08b897ecabb3e3158ac4862bb6d2984dcd992e661b556343ed045b373df3"
metafile = true

[[files]]
file = "mods/calamitymusicdisc.pw.toml"
hash = "d40f6fff5af56c6849db970d2c5d13015755c3ff0859711bd16866d67e9c18ad"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
hash = "ade3149a936c8cab5de918e3e99c85e5b3c76268040bbe34747508918499939f"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "6bf0dfc257bbc9ba40dafe07c3ebf5436af5456182656f00d20930e489d9a305"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "ff8be8ad7eeed3ffc1d624fb30c06ee1de0a871f8fafa354f9002452f645c79a"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "8b8efc109b77ad3634c9434fb5b49c50e72b2a3c2c3e81f69d9a4e298e2e5fde"
metafile = true

[[files]]
file = "mods/chisels-bits-for-fabric.pw.toml"
hash = "12a81bd228982ec983c11a5f97bbdf9f6e1bd8343dcaf77bce10d41ca0e51698"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "69b621472e07a0fff7c6274b828f8003f82fa93c21240906c6d8858a52b6d1bf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "5b137b69e241c9e7d0f6f1d33f40ab56956f51e8f4bb51608721dd4df0cc897e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "1271fe47b105f5eb46d659ea79b0e7323a56288830d6af991f6bccc9d23eddc6"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "bee33aeaef617b11b4b99f59e9443b354140630fddc0ddf95d60314cd201abab"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "16b5415c08542ae254e2765b94175deb393ba9dbbf57fc7f364e334050e7a9da"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "c43aa04ade603a93bae3f22cd6f120660a242f16150d0484a273667c67215645"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "24506087e646ea82007cc75b7affc7803f5a2cd86dbe9711017e1fb800fc996d"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "446fab8551eac0486998922b625c7e9a5d7bce4f3dd8fb8455a95cd49e26b55c"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "47fd33da68d0b13cdffd4124f5bc9cff64caa2878ce7e979ba8092400c2ae1eb"
metafile = true

[[files]]
file = "mods/energized-power.pw.toml"
hash = "dcfeece63f635643c13bfa0b91ca355c86d8ca60d2a9aa7384d813bbfbc3273e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "dd1641d5b805871931a17dc9bf9eea2d3ff8604a654bdae5262cbf6db6d19091"
metafile = true

[[files]]
file = "mods/eureka-ships.pw.toml"
hash = "d5cad55d8bb063133e0de110721b5e51da35ef105187076d4fdc821756889c45"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1ee56d5feb0ede9397b26f3c5b7543a3556088146d154b55172ef0e8b1a97705"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "13389866198e1f1310cccf22f9160ea976340bd535b11b420097a3c50df3d6cf"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "191b276151cccd6c812e4cd220ab5cc5e694e42d947bf35d77be2a8447720647"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "51fae398a6df96b056e5cd119b59187c0a7f26fd210ab1c5406d3de2e8e271af"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "63a06d00526a9315b5906d03b9921d5b957c0cd30cbd392f745887be21d4935f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e96d6fe991c6f55e79b0cf760d10186a4c42aded2a81d1914657e5c427af5f5b"
metafile = true

[[files]]
file = "mods/iris-flywheel-compat.pw.toml"
hash = "847552c175b3b4c35e8106a75dbd1243b530487105871650fa7cbb52c2418b3a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "0ba6a898d408aa0bfdaaf70721c1e46c47636e01ac7b5244b6b43994704882af"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "bc64bb0f72acc944a8f6fd48e6147c698efd0456d6c63c27847bcaa896addd84"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d5026c3ae985be49c9c6375af4f52795bd771858cba863fb6cba9add950bf3da"
metafile = true

[[files]]
file = "mods/jime.pw.toml"
hash = "18c1191fe6b64de906b8c372153a2ac2071b148f6e66058ef2cae4109d0ebb5f"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "e3f65e290d2c9b0fe6602e7b712433a0102ce7e2b33c12e2915aff173d5d99aa"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/lithosphere.pw.toml"
hash = "a65049201de5c60f1722b7dcfe63ebd2adcdc1374342fb255ffb5a2885b92899"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "ce7813de127c80a2826beab1f661740574c34ff39804329dece441f098ab2d45"
metafile = true

[[files]]
file = "mods/man-of-many-planes.pw.toml"
hash = "b5c9a3c5fca9ac187b41d28d8ed913346a0756b32cb4c406429eb944c8b8f10c"
metafile = true

[[files]]
file = "mods/mcpitanlibarch.pw.toml"
hash = "af97099f49e0a43df51ed00607b4f9dab2383a51370d978ec781f9dd1e15faa8"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "e5a22852dcbe06ae2903e7f09d8066397bd255ea33ecdc74f2bd994a128d0ef1"
metafile = true

[[files]]
file = "mods/ore-vein-miner.pw.toml"
hash = "88685d69407ef1d2f28f27949769b967f151bc4fbe9d04ae24d643dbd5c45952"
metafile = true

[[files]]
file = "mods/origins-plus-plus.pw.toml"
hash = "d8a34ad6d267b6d1404aa09e9539d292d807230d8c4104e1d1d9dba16126a713"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "becdcc272e47d41503c7701105bd4cab68380aa1e0c6db7d7edbf06cb4d781e6"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "c24d537ff9c54ebfc6b244ded3d82a47a2f4f4912b1662da18922038688ae8e0"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "e263156892782aff6124ef4fe589527a07383c66ead1ed5b93a5d15dcb03b8f7"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "354e2e52fa611a73a50059873090cc3605f1868cbae61baeb952e2ec162ded31"
metafile = true

[[files]]
file = "mods/redstonepen.pw.toml"
hash = "db5d6b54f58a48e38950a9510b971be7f97a8c5180f2905f788dc1d75c4ad5fc"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "fff5ef0fc18058977333e359533555d57ff02cf8e0998f00c2d203c3b65f240e"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "6650ad633fcf6230cb490519a0e14cfb2a5e6fe9ffc89b041daf3928f47a0fca"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "06cf9fdd7ac69b428f19ba61c30e9f78d63cb05df4cb7500b4bd4cc4a03d6b13"
metafile = true

[[files]]
file = "mods/simple-copper-pipes.pw.toml"
hash = "5a0e72df7f2cb9a2e016e826b223ad20947ef3a1520ed4296468405f01b87007"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "816002a1dd90d02914c570974c6e413b8d712242bad3c01a591d1b76f46ba65d"
metafile = true

[[files]]
file = "mods/spacecube.pw.toml"
hash = "2e138e8d8bbc2308bb4bf7775eaffdae3d1aacb687bf94794e265d4c4672a44b"
metafile = true

[[files]]
file = "mods/still-life.pw.toml"
hash = "2c6a3d95de4ea6b34eb9f6947efe7701d6cf253369429574ce48c6f53049d6e2"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "7a4038f8a262da3ad538cbb67f514b4e49cb8c65102876f2664379cf823145b4"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "3f092115f91d9900395b2eab5105d73adbaa37fe4cbcf26cb1c743d2e9baa4b8"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "2cce9aa9d219cb91d9e7c67dd6d24b220cddaa4e6e8c5764e015e8cd5a01e577"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "5497d3ab3f39171289a05ce996b3a757e960c2200a3d9435124762f056a74b4e"
metafile = true
