hash-format = "sha256"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "ff4b1002e2ca246ab15c2d9889832e873e49cb05fe9916f3282f92bd53294ca8"
metafile = true

[[files]]
file = "mods/adorn.pw.toml"
hash = "108c035c32a20c623bb13c26c8a7a37426f3d50495273fb1e1cb5e9f59e52d8f"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "ddb73a24312769d0023e70d764db13e2de3cfe271c1e7e7c6ae9bd4e1201cd20"
metafile = true

[[files]]
file = "mods/altorigingui.pw.toml"
hash = "95d278261dad118bd5ce0474d4f8d05ceab0c81e16159cb94182b550187cd473"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "9870f77dc7c79097b871ef30cf12c1f3f6f7ca87101c4d4c6584c00bcb5b569d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "f3f98ccb142504aa558f3250b5a9bcda5d9fb45634562a4b7f886489575f6f5a"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "f53692469637eda8ca8e113738fc02e4a08a2093781da80c96c8fdf0671b65b2"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "ab1e22cc66189067e002a204c70c553cc7cc0e738bd602f405d7cc37561260be"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "dd8057c40ff94e9a21a121583884f71c9a6b1eaa6f913ef46c5d1f9b37fe487f"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "64a244469b7ce7be7e6ceabedd69d17e573a0b92d6e29c661fc6c490afa965d8"
metafile = true

[[files]]
file = "mods/calamitymusicdisc.pw.toml"
hash = "cb9cb1506833aaa1b5e03b7ca44fbbbae1d83c063ec6661ded8154a8b5db0ff0"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
hash = "01aa15f05037f6d9ee92007ddfe9e5584ad2f07a24456e1cbadd86f9f2173c88"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "5ba003768a235ab0d811218191166f9aefa4c9a2509341fbba1efd80e18d3676"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "30ad9dfe5d3e7aa49aed43266c6e3bd76187f9126434e1652d44fa00ca29bf5c"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b1581bbfae9d16690f4022536da6567f000130c4ea5e04d92177c1bc61fea709"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "2801e258fc6e9b96900865e1dce5bc9167f01e993b8aad2672b5d671d3524bf8"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "97fa95db99748805bfb5dd844fee528d6fb67c492e6366681ef657bbc7820a5f"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "af83eb1ea0f7a36e4424248c744c1cbebb5045d361e843b873d4d89bf65ad8ad"
metafile = true

[[files]]
file = "mods/energized-power.pw.toml"
hash = "7761f7b81e7577ad9fc1865cfa9c23c65e51a63386c3809cf9afc82cb7bd68ab"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7eefb0f3d1b793f7dc57ee7cf368d055c9b1bf3556f61179f38f1c49c163c1bd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1ee56d5feb0ede9397b26f3c5b7543a3556088146d154b55172ef0e8b1a97705"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "41e364c29ac783e302b4dfd7e1832ca3d814870acdfc4591e4791eb80ce445f7"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "ca3ca3f51541688c45a81c541ff46660853106ebda282dfd59da00f5c9c0a9cd"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f644c401c3ef437f661564171abc8be8f13ad71cb67461734ab402d2ebe7cc47"
metafile = true

[[files]]
file = "mods/jime.pw.toml"
hash = "d9e6d5f471c33c332c5bffe9d821745dbbf78ae4170c61b4ba3cc5a3f6de27f8"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "c1cc1e05c95d769dd4929825e6a85d5ac8023d4a018569f40dd7bd972a81655e"
metafile = true

[[files]]
file = "mods/lithosphere.pw.toml"
hash = "11e8f7c2a2214f3133188ca8d045c9171eca8988fbae8a13572e56129b8b9910"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "bc91fa90e9f26f3ff3690c1a508647a162cd63dc36d815b8af0d6f5e01e5ecbf"
metafile = true

[[files]]
file = "mods/man-of-many-planes.pw.toml"
hash = "9c75a2572604803f8e03d00c98ef3b971fad40f9560676d564064a26e32b7a20"
metafile = true

[[files]]
file = "mods/mcpitanlibarch.pw.toml"
hash = "d7a44ab25cd968370acdf82806c24c9e78c90924d79c4575f8ccd77845145d4e"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/ore-vein-miner.pw.toml"
hash = "54c06381a1e6e028dc653c01700e64c8dcfdd661961773cedf4713f76eb05e7a"
metafile = true

[[files]]
file = "mods/origins-plus-plus.pw.toml"
hash = "dfb5b57715a0356b610695039b3c4eef72dc6ffe4c88d9bd94227bbb4a562c03"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "faadbd329bd9b454d469c4ebdbcee1aa718b922c86ba68db8284152cb28ecf75"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "43b4a9ca9aaac5a16ed067aee92cafaf30d6166d62d7fa851179c6257ed75b59"
metafile = true

[[files]]
file = "mods/redstonepen.pw.toml"
hash = "6054f41427006d33365bf20810e5c6ad7e7e3019ece736b39b0c45ddf438cd4e"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "77a658a9d9cec5037136b95c42d1dff26dbf4010f17ecb2116bebf69178a03ba"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "3159f65be74fdf8c382f2079d9db965972c8612e661f126be522ae37a73c34f8"
metafile = true

[[files]]
file = "mods/simple-copper-pipes.pw.toml"
hash = "ac586a552c30ff577efd8f843350304f112efb133062ca7a357a31628a04368f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/spacecube.pw.toml"
hash = "227ba7f369cc2b4e707b1269939afa1780972983cdde4f696802fff04a960fb8"
metafile = true

[[files]]
file = "mods/still-life.pw.toml"
hash = "79129a6a9c3832ca239d2903cf7fa92b413d16929b98e4b10e19b50f4856fb4a"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "ce08171df6d0816ffc228cd408ba15cfae26abc0e4dcc975bac6eeaffdfe16dd"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "d6ddde622109dc5072e84fc6493c44950314594864a74495d898bcefbd3f2e8b"
metafile = true
