name = "1.20.1"
author = "Starlight"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e57b972a4ecb7433a79954d1477112066f30e36f46b22724b8424a916406f5cc"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
